### PR TITLE
#57 Upgrade to Java 9

### PR DESCRIPTION
**Pull request by giovannipessiva**
Upgraded to Java 9, as for #57, using a property so that it can be easily customized. There was no need to change the source code 
:beers:

### CODE REVIEW

**Comment by giovannipessiva** [comment]
The Travis build fails with this error:

> [ERROR] Plugin org.jacoco:jacoco-maven-plugin:0.8.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.2: Could not transfer artifact org.jacoco:jacoco-maven-plugin:pom:0.8.2 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/repos/central/data/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

It seems strange to me, maybe it's a temporary certificate validity issue.

**Comment by feldoh** [comment]
I've had a look at the failure. I suspect it's due to this: https://travis-ci.community/t/java-9-build-failing-with-https-certificate-exception/4364/2 basically the OracleJava9 isn't supported on the travis build base so either you need to swap to openjdk which may break the JavaFX stuff unless you make more changes or hard-code `dist: trusty` in the travis.yml.

**Comment by giovannipessiva** [comment]
Mmh sorry I don't have experience with JavaFX and OpenFX, so I will commit the configuration to revert the distibution to Trusty. Let's see how that goes

**Comment by feldoh** [comment]
Okay gw. So now I’d guess the version of findbugs isn’t compatible. You may need to upgrade more than just that one plugin but it should just be a case of upgrading some of the plugins. I’d help you work out which but I’m on my honeymoon and my phone doesn’t have maven XD

**Comment by giovannipessiva** [comment]
So Ubuntu Xenial Xerus is the new Travis default dist, and as default it uses OpenJDK11: https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
I have committed an upgrade to that (so also an upgrade to OpenFX), take it as a present for your wedding :smile:
I have run the app and it seems to work; I have not found a way to build a runnable jar, nor to build a native binary, though :confused:

**Comment by feldoh** [comment]
Excellent work, thanks for all the hard work!

**Pull request merged**
